### ISSUE TITLE
Goodies: Update "Basic Tutorial" / "Quick Start" to use `structured_answer`

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/duckduckgo-documentation#159]
Like in URLDecode: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/URLDecode.pm#L45...L50

![screen shot 2014-11-20 at 12 07 30 pm](https://cloud.githubusercontent.com/assets/81969/5129122/d2156f7c-70ad-11e4-82f1-aae89f62afca.png)

**Comment by moollaza** [comment]
Closing. We have new plans for the quickstart and basic tutorials
