### ISSUE TITLE
Language API?

### ISSUE THREAD

**Issue by andrey-p** [duckduckgo/duckduckgo-documentation#180]
I was looking through the DDG RequestHandler code (I was curious about the other kinds of parts of the query you could handle besides the remainder, as mentioned in the [Spice basic tutorial](https://github.com/duckduckgo/duckduckgo-documentation/blob/master/duckduckhack/spice/spice_basic_tutorial.md#define-the-handle-function)). I noticed there's a Language API exposed with the `$lang` variable, similar to the `$loc` one for the Location API.

I was thinking it might be pretty useful for IA developers to know that this feature exists, especially if you're interested in getting non-English language speakers to use DDG.

Would you like me to do a quick writeup of that feature and stick it in a PR?

**Comment by MrChrisW** [comment]
@andrey-p Thanks for your interest in contributing. A similar question was actually asked on our mailing list. I'll paste @moollaza response here. 

>Right now though, all our Instant Answers provide English results (translation will come later) so initially let's move forward with just English answers. 

It may be useful to document this function however it won't get much use currently.

**Comment by andrey-p** [comment]
@MrChrisW That's fair enough I guess. Only the Translate IA seems to be using it at the moment.

I'm still up for doing that writeup, of course, and I could add something like @moollaza's response as a disclaimer at the top, something like:

> While for the time being DDG only deals with Instant Answers in English, it might be useful to know the user's locale [...]

At the very least it could save you some documentation effort a couple of years down the line. :)

**Comment by MrChrisW** [comment]
@andrey-p Sure, more documentation is better then none :laughing: 

We'll wait to see what @moollaza thinks :+1:

**Comment by moollaza** [comment]
@andrey-p yes please! You're of course welcome to document it. There may be other potential uses for it, but I would suggest devs use it to modify the language of a result, because we can't know for certain if that locale's language is also the user's preferred language.
