### ISSUE TITLE
Remove references to CouponMountain

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/duckduckgo-documentation#187]
CouponMountain IA was removed, documentation requires updating. Self reminder to fix!

+ https://github.com/duckduckgo/duckduckgo-documentation/search?utf8=%E2%9C%93&q=CouponMountain

+ https://github.com/duckduckgo/duckduckgo-documentation/blob/master/duckduckhack/spice/spice_templates_overview.md

+ https://github.com/duckduckgo/duckduckgo-documentation/blob/master/duckduckhack/resources/how_to_qa.md

**Comment by moollaza** [comment]
@MrChrisW thanks for this!

**Comment by MrChrisW** [comment]
Resolved in #196
