### ISSUE TITLE
Guidance about Goodie performance and resource consumption should exist

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/duckduckgo-documentation#191]
Following on from the conversation about the words goodie I think some rough guidance should be added to the Goodie documentation; the closest we've got at the moment is @moollaza here: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/816#issuecomment-72789769

Can we get some "firm" boundaries defined and doc'd?

**Comment by moollaza** [comment]
Yup, I have a task to add it, but for now 50ms is a hard limit on max execution time

**Comment by moollaza** [comment]
Will get back to you on memory usage...

**Comment by moollaza** [comment]
Memory will need to be dealt with on a case by case basis, but anything over 1Mb should be flagged for further inspection and consideration.

**Comment by mintsoft** [comment]
@moollaza Cool; any thoughts on a consistent way of getting metrics on these things for the docs?

**Comment by moollaza** [comment]
@mintsoft I'm really not sure about the best way to determine those. Will ask the eng team if they have any suggested tools/methods

**Comment by moollaza** [comment]
Should be fixed now :+1:
