### ISSUE TITLE
Spice template examples - Incorrect

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/duckduckgo-documentation#205]
Many of the Spices listed under certain example "template groups" as examples use different templates.  

Example:
Gravatar spice is listed as using the [`info` template](https://github.com/duckduckgo/duckduckgo-documentation/blob/master/duckduckhack/spice/spice_templates_overview.md#example-uses-of-the-info-template-group) however it actually uses the [`base` template](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/gravatar/gravatar.js#L48).

**Comment by moollaza** [comment]
Will fix this soon with the coming docs updates! Thanks for noticing :+1:

**Comment by MrChrisW** [comment]
@moollaza New documentation! Amazing :+1:

**Comment by zekiel** [comment]
Happy to finally close this if @MrChrisW is satisfied!

**Comment by MrChrisW** [comment]
@zekiel I'm satisfied! 

![](http://media.giphy.com/media/mXuPwCWpd2WLV5WCSQ/giphy.gif)
