### ISSUE TITLE
Spice Basic Tutorial Typo

### ISSUE THREAD

**Issue by blakeprobinson** [duckduckgo/duckduckgo-documentation#238]
The Invoke an Immediate Function section of the Spice Basic Tutorial has a typo in the text:

"After creating our module, we then we turn on JavaScript's Strict Mode which also offers various benefits."

It should probably read:

"After creating our module, we then turn on JavaScript's Strict Mode which also offers various benefits."

**Comment by MrChrisW** [comment]
Hi @blakeprobinson, thanks for reporting the typo, this has now been fixed (in #239 )

Just so you're aware the DDG documentation is currently undergoing some major updates :+1:

**Comment by blakeprobinson** [comment]
You're welcome @MrChrisW.  Thanks for the heads up.
