### ISSUE TITLE
clarify "erase any pre-filled content" 

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/duckduckgo-documentation#257]
On the cheat sheets page: https://duck.co/duckduckhack/goodie_cheat_sheets there's a line: 

"Erase any pre-filled contents, and enter the values for your cheat sheet using the cheat sheet JSON syntax. "  

but we didn't yet tell the user to use an example json file. So when you, "create a new file" it will create itself as a blank file. We should probably provide a reference to copy+paste and then use the Syntax file to help annotate. 

OR comment out vim.json in the same style as the syntax guide. 

thoughts? //cc @talsraviv

**Comment by zekiel** [comment]
to clarify my own comment :)  I'm saying that we reference the Syntax guide and the Vim.json file but not in the (seemingly) correct order.

**Comment by talsraviv** [comment]
I see what you're getting at. I wrote this to be as beginner-friendly as possible, so using the Codio `File > New File` menu, you get this when the file extension is .json:

![screen shot 2015-06-01 at 11 33 22 am](https://cloud.githubusercontent.com/assets/1065307/7923835/25277a48-0852-11e5-802c-585c6f44687d.png)

So I wrote to erase anything Codio might pre-fill

**Comment by talsraviv** [comment]
Maybe there's a way to modify the main DDH box that gets cloned to prevent this?

**Comment by talsraviv** [comment]
cc @moollaza

**Comment by zekiel** [comment]
i just meant in the docs :)

**Comment by moollaza** [comment]
We could definitely create a template for the docs. One step further would be to improve DuckPAN:
i.e.  `duckpan new --cheatsheet` or similar, which generates a named JSON file in the CheatSheets dir?

**Comment by talsraviv** [comment]
Ah gotcha. Yeah duckpan is a cool idea for down the road. 
What I'll do for now is encourage contributors to copy the code block and replace their values (and comment out ellipses and so on that would break it)
