### ISSUE TITLE
clarify that quotes and brackets need escaped separately

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/duckduckgo-documentation#259]
We specify that brackets need escaped w/ a backslash but need to also specify the same for quotes. 

It's a little unclear for non-tech folk, I suppose.

**Comment by moollaza** [comment]
We may want to link to a JSON syntax page to explain that certain characters need to be escaped for JSON, while other, like brackets, are escaped for the CheatSheet parser...

**Comment by moollaza** [comment]
Fixed in https://github.com/duckduckgo/duckduckgo-documentation/pull/261
