### ISSUE TITLE
Investigate what's involved in moving this repo out of publisher deployment

### ISSUE THREAD

**Issue by jbarrett** [duckduckgo/duckduckgo-documentation#263]
We could probably have duck.co render this xslate directly (with caching?)

**Comment by moollaza** [comment]
@jbarrett just to clarify, the docs themselves don't actually use xslate  -- this repo is pure Markdown which we runthrough MarkDent to produce  HTML. That get's passed along via Publisher (into an xslate template which wraps it all in the CommPlat) to produce the final view

https://metacpan.org/pod/Markdent
