### ISSUE TITLE
Some rendered code snippets have a funny character at the end

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/duckduckgo-documentation#276]
Noticed this here: https://duck.co/duckduckhack/templates_reference#variants

![templates_reference___instant_answer_display___duckduckhack](https://cloud.githubusercontent.com
/assets/873785/8167218/c4c480b4-136a-11e5-96f9-337dd0254fa5.png)

/cc @talsraviv

**Comment by talsraviv** [comment]
Can't see screenshot - reattach?

**Comment by akashnimare** [comment]
@moollaza Screenshot Not found?

**Comment by moollaza** [comment]
Not sure what happened with the picture, but everything seems OK now.
