### ISSUE TITLE
Clarify nested and curly brackets

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/duckduckgo-documentation#281]
https://twitter.com/gumnos/status/611513322563698688

**Comment by talsraviv** [comment]
"@duckduckhack Could docs detail what should happen with nested […{…}…] in a string and when to use […] vs. {…} in strings?"

**Comment by talsraviv** [comment]
Alright - I've clarified the second part in this PR https://github.com/duckduckgo/duckduckgo-documentation/pull/282

@moollaza what is the answer to his first part?

**Comment by eveninglily** [comment]
Should this be closed? The PR was merged a long time ago https://github.com/duckduckgo/duckduckgo-documentation/pull/282

**Comment by talsraviv** [comment]
👍
