### ISSUE TITLE
Spice Frontend Walkthroughs not linked

### ISSUE THREAD

**Issue by altern8tif** [duckduckgo/duckduckgo-documentation#284]
Only Walkthrough#1 seems to be accessible.  Clicking on the other 3 walkthroughs doesn't seem to bring me to the others.

I see it in the `spice_frontend_walkthroughs.md` file but not able to view it on [DuckDuckHack](https://duck.co/duckduckhack/spice_frontend_walkthroughs#walkthrough-3-airlines-medium) itself.

**Comment by moollaza** [comment]
@altern8tif you're correct, the other walkthroughs are very old so they're commented out. We plan to update them but haven't gotten around to it yet.

We should definitely remove any broken/stale links though!

**Comment by altern8tif** [comment]
Resolved with the new docs :+1:
