### ISSUE TITLE
Arrow keys broken in Cheat sheet doc

### ISSUE THREAD

**Issue by iambibhas** [duckduckgo/duckduckgo-documentation#293]
Although the arrows appear correctly [here](https://github.com/duckduckgo/duckduckgo-documentation/blob/master/duckduckhack/goodie/goodie_cheat_sheets.md#arrow-keys), this is how they appear in the generated doc - 

![selection_063](https://cloud.githubusercontent.com/assets/357253/8510258/518a8da2-22f9-11e5-9ff1-25d05e9d2690.jpg)

**Comment by moollaza** [comment]
@iambibhas thanks for noticing! I've pushed a fix. Should be live soon:

![creating_cheat_sheets___goodie___duckduckhack](https://cloud.githubusercontent.com/assets/873785/8531312/6d847576-23f4-11e5-8a27-fbb28ea0803b.png)

**Comment by moollaza** [comment]
/cc @talsraviv looks like we can't put ASCII/Unicode chars into the docs as plaintet. :disappointed: 

We'll neet to use the HTML Entities (e.g. `&larr;`) where applicable. Unfortunately we can't put any in code blocks though as the won't get rendered as HTML`

**Comment by iambibhas** [comment]
@moollaza the doc generator doesn't support unicode characters?

**Comment by moollaza** [comment]
@iambibhas now that I think about it a little more, it's likely a bug in our parsing code, not Markdent.  Looking into it now

**Comment by moollaza** [comment]
After quite some time fighting with Perl and UTF8 encodings/decodings I believe I've now fixed our documentation generator's handling of UTF8 in the docs.

Will revent this fix later to verify, once my PR has been merged.

**Comment by iambibhas** [comment]
:+1:
