### ISSUE TITLE
Markdown Strikethrough doesn't render properly

### ISSUE THREAD

**Issue by DavidGinzberg** [duckduckgo/duckduckgo-documentation#298]
The ~~strikethrough~~ (double tilde) markdown is not rendering on the duckduckhack site. Instead it is displaying as \~\~plaintext\~\~, as seen in the [Cheat Sheet Ideas section](https://duck.co/duckduckhack/goodie_cheat_sheets#cheat-sheet-ideas)

**Comment by DavidGinzberg** [comment]
The [Github flavored markdown](https://help.github.com/articles/github-flavored-markdown/) documentation mentions that strikethrough using double-tilde is an addition that is not part of standard markdown. Not sure the flavor/implementation used on the documentation page but that may be relevant.

**Comment by MrChrisW** [comment]
Cheers for reporting this @DavidGinzberg 
Assigning to @moollaza to investigate - markdown parser :+1:

**Comment by moollaza** [comment]
Looks like the Markdown parser we use does not implement the ~~ syntax. For now, I've switched them to `<del>` and everything seems to be working!

Thanks a lot for reporting this @DavidGinzberg
