### ISSUE TITLE
DuckPAN installation in Spice tutorial should link to https://duck.co/duckduckhack/installing_duckpan instead

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/duckduckgo-documentation#68]
Step 1 in https://duck.co/duckduckhack/spice_testing_triggers should link to https://duck.co/duckduckhack/installing_duckpan instead so that the instructions to install DuckPAN are consistent.

**Comment by moollaza** [comment]
This has all changed. Should be fixed now :+1:
