### ISSUE TITLE
Goodie & Spice Perl Helpers

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/duckduckgo-documentation#99]
Currently Spice and Goodies have a couple helper functions defined here: https://github.com/duckduckgo/duckduckgo/blob/45c44d14da86e19ccff8c07682722140b17bc020/lib/DDG/Meta/Helper.pm

We should probably add these to the Spice API and create a Goodie API page as well that contains `share`, `html_enc` and `uri_esc`

**Comment by zekiel** [comment]
@moollaza  close?
